# Generated by Django 3.2 on 2022-12-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='pays',
        ),
    ]
