# Generated by Django 3.2 on 2022-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_remove_depense_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.CharField(max_length=255, verbose_name='Montant depensée'),
        ),
    ]
