# Generated by Django 4.1 on 2024-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_depense_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='type',
            field=models.CharField(choices=[('', 'Séléctionner le type'), ('VOL', 'VOL'), ('BATEAU', 'BATEAU')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
