# Generated by Django 4.1 on 2024-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_depense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.PositiveIntegerField(verbose_name='Montant depensée'),
        ),
    ]
