# Generated by Django 4.1 on 2024-02-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agences', '0003_remove_agence_adresse'),
        ('depenses', '0006_alter_depense_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='agences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
