# Generated by Django 4.1 on 2024-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0008_rename_type_depense_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='types',
            field=models.CharField(choices=[('', 'Séléctionner le type'), ('Vol', 'Vol'), ('Bateau', 'Bateau')], max_length=255),
        ),
    ]
