# Generated by Django 4.1 on 2024-04-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0008_alter_conteneur_cloture'),
        ('depenses', '0009_alter_depense_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='conteneurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteneurs.conteneur'),
        ),
    ]
