# Generated by Django 4.1 on 2024-04-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_depense_conteneurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='types',
        ),
    ]
