# Generated by Django 4.1 on 2024-04-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0008_alter_conteneur_cloture'),
        ('depenses', '0011_remove_depense_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='conteneurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteneurs.conteneur'),
        ),
    ]
