# Generated by Django 4.1 on 2024-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0002_alter_conteneur_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefConteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ref_conteneurs',
            },
        ),
        migrations.AddField(
            model_name='conteneur',
            name='prefixe',
            field=models.CharField(default=1, max_length=255, verbose_name='Préfixe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conteneur',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code du conteneur'),
        ),
        migrations.AlterUniqueTogether(
            name='conteneur',
            unique_together={('code', 'prefixe')},
        ),
    ]
