# Generated by Django 4.1 on 2024-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0003_refconteneur_conteneur_prefixe_alter_conteneur_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='libelle',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
