# Generated by Django 4.1 on 2024-02-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0004_conteneur_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
