# Generated by Django 4.1 on 2024-02-29 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annees', '0001_initial'),
        ('conteneurs', '0005_alter_conteneur_libelle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conteneur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='annees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annees.annee'),
        ),
        migrations.AlterUniqueTogether(
            name='conteneur',
            unique_together={('code', 'annees')},
        ),
        migrations.RemoveField(
            model_name='conteneur',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='conteneur',
            name='prefixe',
        ),
    ]
