# Generated by Django 4.1 on 2024-02-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0006_alter_conteneur_unique_together_conteneur_annees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='cloture',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
