# Generated by Django 4.1 on 2024-02-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0007_conteneur_cloture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='cloture',
            field=models.BooleanField(default=False, verbose_name='Cloturé ?'),
        ),
    ]
