# Generated by Django 4.1 on 2024-02-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'codelot',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codelot', models.CharField(max_length=100)),
                ('poids_lot', models.CharField(max_length=100)),
                ('nombre_colis', models.IntegerField()),
                ('dates', models.DateField(verbose_name='Date')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('etat_embarqment', models.CharField(default=0, max_length=10)),
                ('date_etat_embarqment', models.DateField(blank=True, null=True)),
                ('heure_etat_embarqment', models.DateTimeField(blank=True, null=True)),
                ('agences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agences.agence')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_etat_embarqment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_etat_lot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lots',
            },
        ),
        migrations.CreateModel(
            name='DetailLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.coli')),
                ('lots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lot')),
            ],
            options={
                'db_table': 'detail_lots',
            },
        ),
    ]
