# Generated by Django 3.2 on 2022-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise")),
                ('abreviation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abreviation')),
                ('logo', models.ImageField(upload_to='logo', verbose_name="logo de l'entreprise")),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Web')),
                ('rccm', models.CharField(blank=True, max_length=255, null=True, verbose_name='RCCM')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('siege', models.CharField(blank=True, max_length=255, null=True, verbose_name='Siège')),
                ('orabank', models.CharField(blank=True, max_length=255, null=True, verbose_name='N° de compte ORABANK')),
                ('access', models.CharField(blank=True, max_length=255, null=True, verbose_name='N° de compte ACCESS BANK')),
                ('bci', models.CharField(blank=True, max_length=255, null=True, verbose_name='N° de compte BCI')),
                ('logo_entete', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo entete')),
                ('services', models.TextField(blank=True, null=True)),
                ('header_color', models.CharField(blank=True, max_length=255, null=True)),
                ('header_color_left', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
    ]
