# Generated by Django 3.2 on 2022-12-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='access',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='bci',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='header_color',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='header_color_left',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='logo_entete',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='orabank',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='siege',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='telephone',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse_guinee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Guinée'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse_paris',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Paris'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone_guinee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Guinée'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone_paris',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Paris'),
        ),
    ]
