# Generated by Django 3.2 on 2022-12-17 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agences', '0003_remove_agence_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(verbose_name='Montant déposé')),
                ('dates', models.DateField(verbose_name='Date')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('agences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agences.agence')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depots',
            },
        ),
    ]
