# Generated by Django 3.2 on 2022-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='motif',
            field=models.CharField(max_length=255, verbose_name='Motif'),
        ),
    ]
