# Generated by Django 3.2 on 2022-12-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0002_alter_depot_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='montant',
            field=models.CharField(max_length=255, verbose_name='Montant déposé'),
        ),
    ]
