# Generated by Django 3.2 on 2022-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0003_alter_depot_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='devise',
            field=models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], default=1, max_length=255, verbose_name='Dévies'),
            preserve_default=False,
        ),
    ]
