# Generated by Django 4.1 on 2024-04-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annees', '0001_initial'),
        ('agences', '0003_remove_agence_adresse'),
        ('colis', '0021_colibateau_conteneurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulationbateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, verbose_name='')),
                ('reste', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=65, null=True, verbose_name='Reste à payé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='Montant payé')),
                ('dates', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('agences', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.colibateau', verbose_name='Code du colis')),
            ],
            options={
                'db_table': 'regulationbateaus',
            },
        ),
        migrations.CreateModel(
            name='ReferenceRegulationBateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annees.annee')),
            ],
            options={
                'db_table': 'reference_reglement_bateau',
            },
        ),
    ]
