# Generated by Django 4.1 on 2024-04-18 16:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('etage', models.CharField(max_length=255, verbose_name='Étage')),
                ('code', models.CharField(max_length=255, verbose_name="Code d'accès")),
                ('num_app', models.CharField(max_length=255, verbose_name="N° de l'appartement")),
                ('dates', models.DateField(verbose_name='Date de rendez-vous')),
                ('heure_debut', models.TimeField(verbose_name='Debut')),
                ('heure_fin', models.TimeField(verbose_name='Fin')),
                ('ascenseur', models.CharField(choices=[('', "L'appartement contient-il un ascenseur"), ('Oui', 'Oui'), ('Non', 'Non')], max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
            ],
            options={
                'db_table': 'rendezvous',
            },
        ),
    ]
