# Generated by Django 4.1 on 2024-04-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvou',
            name='email',
        ),
    ]
