# Generated by Django 4.1 on 2024-04-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientsrendezvous', '0001_initial'),
        ('rendezvous', '0002_remove_rendezvou_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvou',
            name='ascenseur',
        ),
        migrations.RemoveField(
            model_name='rendezvou',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rendezvou',
            name='etage',
        ),
        migrations.RemoveField(
            model_name='rendezvou',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='rendezvou',
            name='num_app',
        ),
        migrations.RemoveField(
            model_name='rendezvou',
            name='telephone',
        ),
        migrations.AddField(
            model_name='rendezvou',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientsrendezvous.clientsrendezvou'),
        ),
    ]
