# Generated by Django 4.1 on 2024-04-22 17:56

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
        ('rendezvous', '0003_remove_rendezvou_ascenseur_remove_rendezvou_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseRendezvou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('chauffeurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chauffeurs.chauffeur')),
                ('rendezvous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendezvous.rendezvou')),
            ],
            options={
                'db_table': 'prise_rendezvous',
            },
        ),
    ]
