# Generated by Django 4.1 on 2024-04-22 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
        ('rendezvous', '0004_priserendezvou'),
    ]

    operations = [
        migrations.AddField(
            model_name='priserendezvou',
            name='datejour',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 18, 5, 40, 962314, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priserendezvou',
            name='dates',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priserendezvou',
            name='chauffeurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chauffeurs.chauffeur'),
        ),
        migrations.AlterField(
            model_name='priserendezvou',
            name='rendezvous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rendezvous.rendezvou'),
        ),
    ]
