# Generated by Django 4.1 on 2025-01-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0006_rendezvousmobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvousmobile',
            old_name='heure_debut',
            new_name='heure',
        ),
    ]
