# Generated by Django 3.2 on 2022-11-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro', models.IntegerField(verbose_name='Euro')),
                ('gnf', models.IntegerField(verbose_name='GNF')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tauxs',
            },
        ),
    ]
