# Generated by Django 3.2 on 2022-11-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='euro',
            field=models.IntegerField(default=1, verbose_name='Euro'),
        ),
    ]
