# Generated by Django 4.1 on 2024-04-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=255, verbose_name='Dévise')),
                ('dates', models.DateField(verbose_name='Date')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=0)),
                ('agences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recpepteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decaissements',
            },
        ),
    ]
