# Generated by Django 4.1 on 2024-04-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decaissements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaissement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recpepteur', to=settings.AUTH_USER_MODEL, verbose_name='Recepteur'),
        ),
    ]
