# Generated by Django 4.1 on 2024-04-17 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decaissements', '0002_alter_decaissement_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decaissement',
            name='author',
        ),
        migrations.AddField(
            model_name='decaissement',
            name='emetteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emetteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='recepteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepteur', to=settings.AUTH_USER_MODEL, verbose_name='Recepteur'),
        ),
    ]
