# Generated by Django 4.1 on 2024-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decaissements', '0003_remove_decaissement_author_decaissement_emetteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaissement',
            name='etat',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
    ]
