# Generated by Django 4.1 on 2024-04-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decaissements', '0005_decaissement_validate_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decaissement',
            name='validate_by',
        ),
    ]
