# Generated by Django 4.1 on 2025-01-10 14:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandedevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('poids', models.CharField(max_length=255, verbose_name='Poids')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
            ],
            options={
                'db_table': 'damandedevis',
            },
        ),
    ]
