# Generated by Django 4.1 on 2024-04-22 16:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('telephone', models.CharField(error_messages={'unique': 'Ce numéro existe déjà'}, max_length=100, unique=True, verbose_name='Téléphone')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
            ],
            options={
                'db_table': 'chauffeurs',
            },
        ),
    ]
