# Generated by Django 4.1 on 2024-04-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colis', '0021_colibateau_conteneurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reste', models.CharField(max_length=255, verbose_name='Reste à payé')),
                ('montant', models.CharField(max_length=255, verbose_name='Montant payé')),
                ('dates', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('agences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.coli')),
            ],
            options={
                'db_table': 'regulations',
            },
        ),
    ]
