# Generated by Django 4.1 on 2024-04-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='agences',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=65, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='reste',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=65, verbose_name='Reste à payé'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
