# Generated by Django 4.1 on 2024-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0021_colibateau_conteneurs'),
        ('regulations', '0002_alter_regulation_agences_alter_regulation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='colis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.coli', verbose_name='Code du colis'),
        ),
    ]
