# Generated by Django 4.1 on 2024-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_alter_regulation_agences_alter_regulation_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'reference_reglement',
            },
        ),
        migrations.AddField(
            model_name='regulation',
            name='reference',
            field=models.CharField(default=1, max_length=255, verbose_name=''),
            preserve_default=False,
        ),
    ]
