# Generated by Django 4.1 on 2024-02-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'codecolis',
            },
        ),
        migrations.CreateModel(
            name='Coli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Poids')),
                ('prix', models.CharField(max_length=255, verbose_name='Prix du kilo')),
                ('contenu', models.CharField(blank=True, max_length=255, null=True)),
                ('devise', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Devise')),
                ('nombre_colis', models.PositiveIntegerField(verbose_name='Nombre de colis')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prix_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Montant payé')),
                ('reste', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Reste')),
                ('devise_montantpaye', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('dates', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('montant_euro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en Euro')),
                ('montant_gnf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en GNF')),
                ('etat_enregistrement', models.CharField(default=1, max_length=10)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('heure_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('etat_lot', models.CharField(default=0, max_length=10)),
                ('date_lot', models.DateField(blank=True, null=True)),
                ('heure_lot', models.DateTimeField(blank=True, null=True)),
                ('etat_embarquement', models.CharField(default=0, max_length=10)),
                ('date_embarquement', models.DateField(blank=True, null=True)),
                ('heure_embarquement', models.DateTimeField(blank=True, null=True)),
                ('etat_verification', models.CharField(default=0, max_length=10)),
                ('date_verification', models.DateField(blank=True, null=True)),
                ('heure_verification', models.DateTimeField(blank=True, null=True)),
                ('etat_receptionclient', models.CharField(default=0, max_length=10)),
                ('date_receptionclient', models.DateField(blank=True, null=True)),
                ('heure_receptionclient', models.DateTimeField(blank=True, null=True)),
                ('montant_reglement', models.IntegerField(blank=True, null=True, verbose_name='Montant')),
                ('devise_reglement', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('taux', models.CharField(blank=True, max_length=100, null=True)),
                ('agence_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence2', to='agences.agence')),
                ('agence_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence1', to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destinataire', to='clients.client')),
                ('expditaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expeditaire', to='clients.client')),
                ('user_embarquement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user3', to=settings.AUTH_USER_MODEL)),
                ('user_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('user_receptionclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user5', to=settings.AUTH_USER_MODEL)),
                ('user_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'colis',
                'ordering': ['-id'],
            },
        ),
    ]
