# Generated by Django 4.1 on 2024-02-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_slug_alter_client_email_and_more'),
        ('colis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destinataire1', to='clients.client')),
                ('expditaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expeditaire1', to='clients.client')),
            ],
            options={
                'db_table': 'attributions',
            },
        ),
    ]
