# Generated by Django 4.1 on 2024-02-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0002_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='contenu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
