# Generated by Django 4.1 on 2024-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0003_alter_coli_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='prix',
            field=models.CharField(max_length=255, verbose_name='Prix du kilo en Euro'),
        ),
    ]
