# Generated by Django 4.1 on 2024-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0004_alter_coli_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Prix du kilo en Euro'),
        ),
    ]
