# Generated by Django 4.1 on 2024-02-26 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0005_alter_coli_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='coli',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coli',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids'),
        ),
    ]
