# Generated by Django 4.1 on 2024-02-26 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0006_coli_types_alter_coli_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix du kilo en Euro'),
        ),
    ]
