# Generated by Django 4.1 on 2024-02-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0007_alter_coli_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='code',
            field=models.CharField(error_messages={'unique': 'Ce code existe déjà, valider à nouveau'}, max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
