# Generated by Django 4.1 on 2024-02-29 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0008_alter_coli_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaiColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantite', models.PositiveBigIntegerField(max_length=255, verbose_name='Quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('colis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colis.coli')),
            ],
            options={
                'db_table': 'detail_colis',
            },
        ),
    ]
