# Generated by Django 4.1 on 2024-02-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0009_detaicolis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaicolis',
            old_name='prix',
            new_name='prix_unitaire',
        ),
        migrations.RenameField(
            model_name='detaicolis',
            old_name='quantite',
            new_name='quantite_detail',
        ),
    ]
