# Generated by Django 4.1 on 2024-02-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0010_rename_prix_detaicolis_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaicolis',
            name='quantite_detail',
            field=models.PositiveBigIntegerField(verbose_name='Quantité'),
        ),
    ]
