# Generated by Django 4.1 on 2024-02-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colis', '0011_alter_detaicolis_quantite_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaicolis',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
