# Generated by Django 4.1 on 2024-03-02 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0013_alter_detaicolis_author_alter_detaicolis_colis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaicolis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire en Euro'),
        ),
    ]
