# Generated by Django 4.1 on 2024-03-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteneurs', '0008_alter_conteneur_cloture'),
        ('agences', '0003_remove_agence_adresse'),
        ('clients', '0003_alter_client_email'),
        ('colis', '0014_alter_detaicolis_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecolis',
            name='conteneurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteneurs.conteneur'),
        ),
        migrations.AlterModelTable(
            name='codecolis',
            table='codecolis_bateau',
        ),
        migrations.CreateModel(
            name='ColiBateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Ce code existe déjà, valider à nouveau'}, max_length=255, unique=True, verbose_name='Code')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Montant payé')),
                ('reste', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Reste')),
                ('devise_montantpaye', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('dates', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('montant_euro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en Euro')),
                ('montant_gnf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en GNF')),
                ('etat_enregistrement', models.CharField(default=1, max_length=10)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('heure_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('etat_lot', models.CharField(default=0, max_length=10)),
                ('date_lot', models.DateField(blank=True, null=True)),
                ('heure_lot', models.DateTimeField(blank=True, null=True)),
                ('etat_embarquement', models.CharField(default=0, max_length=10)),
                ('date_embarquement', models.DateField(blank=True, null=True)),
                ('heure_embarquement', models.DateTimeField(blank=True, null=True)),
                ('etat_verification', models.CharField(default=0, max_length=10)),
                ('date_verification', models.DateField(blank=True, null=True)),
                ('heure_verification', models.DateTimeField(blank=True, null=True)),
                ('etat_receptionclient', models.CharField(default=0, max_length=10)),
                ('date_receptionclient', models.DateField(blank=True, null=True)),
                ('heure_receptionclient', models.DateTimeField(blank=True, null=True)),
                ('montant_reglement', models.IntegerField(blank=True, null=True, verbose_name='Montant')),
                ('devise_reglement', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('taux', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('agence_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenceb2', to='agences.agence')),
                ('agence_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenceb1', to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destinataireb', to='clients.client')),
                ('expditaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expeditaireb', to='clients.client')),
                ('user_embarquement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userb3', to=settings.AUTH_USER_MODEL)),
                ('user_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userb2', to=settings.AUTH_USER_MODEL)),
                ('user_receptionclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userb5', to=settings.AUTH_USER_MODEL)),
                ('user_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userb4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'colis_bateau',
                'ordering': ['-id'],
            },
        ),
    ]
