# Generated by Django 4.1 on 2024-03-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0008_alter_conteneur_cloture'),
        ('colis', '0015_codecolis_conteneurs_alter_codecolis_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecolis',
            name='conteneurs',
        ),
        migrations.AlterModelTable(
            name='codecolis',
            table='codecolis',
        ),
        migrations.CreateModel(
            name='CodeColisBateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteneurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteneurs.conteneur')),
            ],
            options={
                'db_table': 'codecolis_bateau',
            },
        ),
    ]
