# Generated by Django 4.1 on 2024-03-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0016_remove_codecolis_conteneurs_alter_codecolis_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaicolis',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colis.colibateau'),
        ),
    ]
