# Generated by Django 4.1 on 2024-03-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0017_alter_detaicolis_colis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaicolis',
            old_name='colis',
            new_name='colis_bateau',
        ),
    ]
