# Generated by Django 4.1 on 2024-03-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0018_rename_colis_detaicolis_colis_bateau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaicolis',
            old_name='colis_bateau',
            new_name='colis',
        ),
    ]
