# Generated by Django 4.1 on 2024-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0019_rename_colis_bateau_detaicolis_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='colibateau',
            name='devise',
            field=models.CharField(default='€', editable=False, max_length=100),
        ),
    ]
