# Generated by Django 4.1 on 2024-03-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0008_alter_conteneur_cloture'),
        ('colis', '0020_colibateau_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='colibateau',
            name='conteneurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteneurs.conteneur'),
        ),
    ]
