# Generated by Django 4.1 on 2024-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0021_colibateau_conteneurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coli',
            name='total_paye',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total paye'),
        ),
    ]
