# Generated by Django 4.1 on 2024-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0022_coli_total_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='colibateau',
            name='total_paye',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total paye'),
        ),
    ]
