# Generated by Django 4.1 on 2024-08-21 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        ('clients', '0003_alter_client_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colis', '0023_colibateau_total_paye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coli',
            options={},
        ),
        migrations.AlterField(
            model_name='coli',
            name='agence_arrive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_agence2', to='agences.agence'),
        ),
        migrations.AlterField(
            model_name='coli',
            name='agence_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_agence1', to='agences.agence'),
        ),
        migrations.AlterField(
            model_name='coli',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Destinataire', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='coli',
            name='expditaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Expeditaire', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='coli',
            name='user_embarquement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coli',
            name='user_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coli',
            name='user_receptionclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coli',
            name='user_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SafeDeleteColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Ce code existe déjà, valider à nouveau'}, max_length=255, unique=True, verbose_name='Code')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix du kilo en Euro')),
                ('contenu', models.CharField(max_length=255, null=True)),
                ('devise', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Devise')),
                ('nombre_colis', models.PositiveIntegerField(verbose_name='Nombre de colis')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prix_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Montant payé')),
                ('reste', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Reste')),
                ('devise_montantpaye', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('dates', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('montant_euro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en Euro')),
                ('montant_gnf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en GNF')),
                ('total_paye', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total paye')),
                ('etat_enregistrement', models.CharField(default=1, max_length=10)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('heure_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('etat_lot', models.CharField(default=0, max_length=10)),
                ('date_lot', models.DateField(blank=True, null=True)),
                ('heure_lot', models.DateTimeField(blank=True, null=True)),
                ('etat_embarquement', models.CharField(default=0, max_length=10)),
                ('date_embarquement', models.DateField(blank=True, null=True)),
                ('heure_embarquement', models.DateTimeField(blank=True, null=True)),
                ('etat_verification', models.CharField(default=0, max_length=10)),
                ('date_verification', models.DateField(blank=True, null=True)),
                ('heure_verification', models.DateTimeField(blank=True, null=True)),
                ('etat_receptionclient', models.CharField(default=0, max_length=10)),
                ('date_receptionclient', models.DateField(blank=True, null=True)),
                ('heure_receptionclient', models.DateTimeField(blank=True, null=True)),
                ('montant_reglement', models.IntegerField(blank=True, null=True, verbose_name='Montant')),
                ('devise_reglement', models.CharField(choices=[('€', '€'), ('gnf', 'GNF')], max_length=100, verbose_name='Dévise')),
                ('taux', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('agence_arrive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_agence2', to='agences.agence')),
                ('agence_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_agence1', to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Destinataire', to='clients.client')),
                ('expditaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Expeditaire', to='clients.client')),
                ('user_embarquement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user3', to=settings.AUTH_USER_MODEL)),
                ('user_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user2', to=settings.AUTH_USER_MODEL)),
                ('user_receptionclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user5', to=settings.AUTH_USER_MODEL)),
                ('user_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safe_delete_colis_vol',
            },
        ),
    ]
