# Generated by Django 4.1 on 2025-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0024_alter_coli_options_alter_coli_agence_arrive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colibateau',
            name='frais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Frais de livraison'),
        ),
    ]
