# Generated by Django 5.0 on 2025-04-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0025_colibateau_frais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='code',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ce code existe déjà, valider à nouveau'}, max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='safedeletecolis',
            name='code',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ce code existe déjà, valider à nouveau'}, max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
