# Generated by Django 4.1 on 2024-04-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depensevol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(verbose_name='Date')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant depensée')),
                ('devise', models.CharField(editable=False, max_length=255)),
                ('motif', models.TextField(verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('agences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depensevols',
            },
        ),
    ]
