# Generated by Django 4.1 on 2024-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depensevols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensevol',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=65, verbose_name='Montant depensée'),
        ),
    ]
