# Generated by Django 4.1 on 2024-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_slug_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Cet email existe déjà'}, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
    ]
