# Generated by Django 5.0 on 2025-04-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ce numéro existe déjà'}, max_length=100, unique=True, verbose_name='Téléphone'),
        ),
    ]
