# Generated by Django 3.2 on 2022-11-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='taux_jour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
