# Generated by Django 3.2 on 2022-12-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        ('accounts', '0002_customuser_taux_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agences.agence', verbose_name='Agence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('agent', 'Agent')], max_length=100, null=True),
        ),
    ]
