# Generated by Django 3.2 on 2022-12-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221202_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
