# Generated by Django 3.2 on 2022-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221202_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(max_length=100, null=True, verbose_name='Prenom et nom'),
        ),
    ]
