# Generated by Django 3.2 on 2022-12-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        ('accounts', '0005_auto_20221202_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agences.agence', verbose_name='Agence'),
        ),
    ]
