# Generated by Django 4.1 on 2024-02-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Année')),
                ('lettre', models.CharField(max_length=100, unique=True, verbose_name="Lettre de l'année pour les bateaux")),
            ],
            options={
                'db_table': 'annees',
            },
        ),
    ]
