# Generated by Django 4.1 on 2024-04-22 14:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientsrendezvou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('rue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rue')),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville')),
                ('etage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Étage')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name="Code d'accès")),
                ('num_app', models.CharField(blank=True, max_length=255, null=True, verbose_name="N° de l'appartement")),
                ('ascenseur', models.CharField(blank=True, choices=[('', "L'appartement contient-il un ascenseur"), ('Oui', 'Oui'), ('Non', 'Non')], max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
            ],
            options={
                'db_table': 'clientsrendezvous',
            },
        ),
    ]
