# Generated by Django 4.1 on 2024-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsrendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsrendezvou',
            name='telephone',
            field=models.CharField(error_messages={'unique': 'Ce numéro existe déjà'}, max_length=100, unique=True, verbose_name='Téléphone'),
        ),
    ]
