# Generated by Django 3.2 on 2022-11-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Prénom et nom du transporteur'),
        ),
    ]
