# Generated by Django 4.1 on 2024-02-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporteurs', '0002_alter_transporteur_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmbarquement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'code_embarquements',
            },
        ),
        migrations.CreateModel(
            name='Embarquement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeembarquement', models.CharField(max_length=255, verbose_name='')),
                ('poids_embarquement', models.CharField(max_length=255, verbose_name='')),
                ('poids', models.CharField(max_length=255)),
                ('nombre_lots', models.CharField(max_length=255)),
                ('etat_reception', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('dates', models.DateField(verbose_name='Date')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('agence_arrive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence4', to='agences.agence', verbose_name='Agence de destination')),
                ('agence_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence3', to='agences.agence')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transporteurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporteurs.transporteur')),
            ],
            options={
                'db_table': 'embarquements',
            },
        ),
        migrations.CreateModel(
            name='DetailEmbarquement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarquements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embarquements.embarquement')),
            ],
        ),
    ]
