# Generated by Django 4.1 on 2024-02-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        ('embarquements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailembarquement',
            name='lots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lot'),
        ),
    ]
