# Generated by Django 4.1 on 2024-04-15 02:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0003_remove_agence_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reglements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 15, 2, 3, 4, 749484, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='agences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
