# Generated by Django 4.1 on 2024-04-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annees', '0001_initial'),
        ('reglements', '0002_reglement_created_at_reglement_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='reference',
            field=models.CharField(default=1, max_length=255, verbose_name=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annees.annee')),
            ],
            options={
                'db_table': 'reference_reception',
            },
        ),
    ]
