# Generated by Django 4.1 on 2024-06-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0021_colibateau_conteneurs'),
        ('reglements', '0003_reglement_reference_referencereception'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='colisbateau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colis.colibateau'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colis.coli'),
        ),
    ]
