# Generated by Django 4.1 on 2024-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0004_reglement_colisbateau_alter_reglement_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='montant_gnf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Montant payé en GNF'),
        ),
    ]
