# Generated by Django 4.1 on 2024-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0005_reglement_montant_gnf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='montant',
            field=models.CharField(max_length=255, null=True, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='reste_gnf',
            field=models.CharField(max_length=255, null=True, verbose_name='Reste à payé en GNF'),
        ),
    ]
