# Generated by Django 4.1 on 2024-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0006_alter_reglement_montant_alter_reglement_reste_gnf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='montant',
            field=models.CharField(max_length=255, null=True, verbose_name='Montant payé en Euro'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='montant_gnf',
            field=models.CharField(max_length=255, null=True, verbose_name='Montant payé en GNF'),
        ),
    ]
