# Generated by Django 4.1 on 2024-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0008_alter_reglement_montant_alter_reglement_montant_gnf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='devise',
            field=models.CharField(blank=True, choices=[('€', '€'), ('gnf', 'GNF')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='reste_gnf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reste à payé en GNF'),
        ),
    ]
