# Generated by Django 4.1 on 2024-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0009_alter_reglement_devise_alter_reglement_reste_gnf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglement',
            old_name='montant',
            new_name='montant_euro',
        ),
    ]
