# Generated by Django 3.2 on 2022-11-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='adresse',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agence',
            name='pays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pays.pay', verbose_name='Pays'),
            preserve_default=False,
        ),
    ]
