# Generated by Django 3.2 on 2022-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agences', '0002_auto_20221130_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='adresse',
        ),
    ]
